version: "3"
services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: hive
    ports:
      - "5432"
  cache:
    image: redis:alpine
    ports:
      - "6379"
